sudo: required

language: python
python: 
    - '3.6'

services:
    - docker
    - postgresql

postgres:
    ports:
        - '5432:5432'

branches:
    only:
        - master


before_script:
    - cat /etc/postgresql/10/main/postgresql.conf

jobs:
    include:
        - stage: "Test"
          script: ".travis/test.sh" 
        - stage: "Deploy"
          script: ".travis/deploy.sh"
          if: (branch = master) AND (type = push)


        # TODO: Encrypt ssh-keys into the git and use them in travis.
        # - fab setup_docker setup_aws_creds
        # - fab authenticate_docker pull_image run_container
